# Configuración mínima para que Netlify reconozca el proyecto
[build]
  publish = "."

# Cabeceras de seguridad básicas
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-XSS-Protection = "1; mode=block"
